workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SugarInsederApp
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.sugarinsiderapp.ivanchai
      vars:
        BUNDLE_ID: "com.sugarinsiderapp.ivanchai"
        XCODE_WORKSPACE: "SugarInsiderApp.xcworkspace"
        XCODE_SCHEME: "SugarInsiderApp"
        APP_STORE_APPLE_ID: 6753351573
        CM_CERTIFICATE: SugarInsiderApp
        CM_PROVISIONING_PROFILE: SugarInsiderApp
        MARKETING_VERSION: "1.0.0"
        BUILD_NUMBER: "10"  # Увеличил еще раз
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Install npm dependencies
        script: |
          npm install

      - name: Clear Metro cache
        script: |
          rm -rf node_modules/.cache
          rm -rf /tmp/metro-*
          rm -rf /tmp/haste-map-*

      - name: Create assets folder with app icons
        script: |
          mkdir -p assets
          # Copy your actual icon instead of using placeholder
          cp icon.png assets/icon.png
          cp icon.png assets/splash.png
          # Create adaptive icon for Android compatibility (though we're iOS only)
          cp icon.png assets/adaptive-icon.png
          echo "✅ Created assets folder with actual app icons"

      - name: Update app.json with version info
        script: |
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "SugarInsiderApp",
              "slug": "sugar-insider-app",
              "version": "MARKETING_VERSION_PLACEHOLDER",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "ios": {
                "bundleIdentifier": "com.sugarinsiderapp.ivanchai",
                "buildNumber": "BUILD_NUMBER_PLACEHOLDER"
              },
              "android": {
                "package": "com.sugarinsiderapp.ivanchai"
              }
            }
          }
          EOF
          sed -i '' "s/MARKETING_VERSION_PLACEHOLDER/$MARKETING_VERSION/" app.json
          sed -i '' "s/BUILD_NUMBER_PLACEHOLDER/$BUILD_NUMBER/" app.json
          echo "✅ Created app.json with version $MARKETING_VERSION ($BUILD_NUMBER)"
          cat app.json

      - name: Remove old iOS folder
        script: |
          rm -rf ios
          rm -rf android

      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --platform ios --clean

      - name: Patch react-native-iap podspec
        script: |
          RNIAP_PODSPEC=$(find node_modules -name "react-native-iap.podspec" -o -name "RNIap.podspec" | head -n 1)
          if [ -f "$RNIAP_PODSPEC" ]; then
            sed -i '' "/RCT-Folly/d" "$RNIAP_PODSPEC"
            echo "✅ Patched $RNIAP_PODSPEC"
          fi

      - name: Patch Podfile
        script: |
          cd ios
          ruby -i -pe 'print "source '\''https://github.com/CocoaPods/Specs.git'\''\n\n" if $. == 1' Podfile

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          
          $PLIST_BUDDY -c "Set :CFBundleShortVersionString $MARKETING_VERSION" $PLIST || \
          $PLIST_BUDDY -c "Add :CFBundleShortVersionString string $MARKETING_VERSION" $PLIST
          
          $PLIST_BUDDY -c "Set :CFBundleVersion $BUILD_NUMBER" $PLIST || \
          $PLIST_BUDDY -c "Add :CFBundleVersion string $BUILD_NUMBER" $PLIST
          
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST || true

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Fetch signing files from Codemagic
        script: |
          keychain add-certificates
          xcode-project use-profiles

      - name: Prebuild React Native bundle
        script: |
          export NODE_BINARY=$(which node)
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output $CM_BUILD_DIR/ios/main.jsbundle \
            --assets-dest $CM_BUILD_DIR/ios

      - name: Build ipa with xcode-project
        script: |
          export NODE_BINARY=$(which node)
          export SKIP_BUNDLING=1
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"

      - name: "📤 Manual upload to App Store Connect with altool"
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          
          echo "========================================="
          echo "📤 Uploading IPA manually using altool"
          echo "========================================="
          echo "IPA: $IPA_PATH"
          echo "Bundle ID: $BUNDLE_ID"
          echo ""
          
          # Получаем API ключи из интеграции Codemagic
          # Они автоматически доступны как переменные окружения
          
          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_PATH" \
            --apiKey $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --apiIssuer $APP_STORE_CONNECT_ISSUER_ID \
            --verbose
          
          echo ""
          echo "✅ Upload completed!"
          echo "⏳ Now wait 5-15 minutes for Apple to process the build"
          echo "🔍 Check status at: https://appstoreconnect.apple.com"
          echo "========================================="

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - delapaska12@yandex.ru
        notify:
          success: true
          failure: true
      # УБРАЛ app_store_connect отсюда - загружаем вручную через altool